application: maksudsite-hrd
version: 14
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin
  
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: media/
  expiration: '365d'
  
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images
  
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /fonts
  static_dir: static/fonts
  
- url: /resources
  static_dir: static/resources

- url: /admin/.*
  script: djangoappengine/main/main.py
  login: admin

- url: /myadmin/.*
  login: admin
  script: djangoappengine/main/main.py

- url: /.*
  script: djangoappengine/main/main.py

admin_console:
  pages:
  - name: Admininistrator
    url: /myadmin